language: node_js

node_js:
  - "8"

script:
      - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  keep_history: false
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master

  dx-scan:
  stage: build
  image: dxheroes/dx-scanner:latest
  script:
    - dx-scanner run --ci
